[project]
name = "backend-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi~=0.128.0",
    "pydantic~=2.12.5",
    "pydantic-settings~=2.12.0",
    "tortoise-orm~=0.25.3",
    "uvicorn~=0.40.0",
]
